export const ADD_SALES = "ADD_SALES"
export const ADD_SALE = "ADD_SALE"
export const UPDATE_SALE = "UPDATE_SALE"
export const UPDATE_SALE_TIME = "UPDATE_SALE_TIME"
export const CLEAR_SALE = "CLEAR_SALE"

export const SET_NUMBER_DEPLOYED = "SET_NUMBER_DEPLOYED"

export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS"
export const SET_CHAIN = "SET_CHAIN"

export const SET_ADMIN_STATUS = "SET_ADMIN_STATUS"
